# Generated by Django 3.0.4 on 2020-10-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_report_case_no', models.CharField(max_length=20)),
                ('local_case_no', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('rural', models.BooleanField(blank=True, null=True)),
                ('Drivers_full_name_Street_Address_City_and_State', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('dL_state', models.CharField(max_length=35)),
                ('driving_license_no', models.CharField(max_length=15)),
                ('file_attached', models.FileField(null=True, upload_to='files/', verbose_name='')),
            ],
        ),
    ]
