# Generated by Django 3.0.4 on 2020-10-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_num', models.CharField(max_length=100)),
                ('request_time', models.CharField(max_length=100)),
            ],
        ),
    ]
