# Generated by Django 3.0.4 on 2020-10-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20201028_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crashreport',
            name='Drivers_full_name_Street_Address_City_and_State',
        ),
        migrations.AddField(
            model_name='crashreport',
            name='Drivers_full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crashreport',
            name='Street_Address_City_and_State',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
