# Generated by Django 3.1.2 on 2020-10-28 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20201028_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestreport',
            old_name='report_num',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='requestreport',
            name='request_time',
        ),
        migrations.AddField(
            model_name='requestreport',
            name='crash_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestreport',
            name='crash_report_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestreport',
            name='driver_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestreport',
            name='inserted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestreport',
            name='search_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestreport',
            name='search_result',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestreport',
            name='updatd_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
