# Generated by Django 3.1.2 on 2020-10-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20201028_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreport',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestreport',
            name='crash_report_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestreport',
            name='driver_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestreport',
            name='search_result',
            field=models.CharField(choices=[('1', 'Not Existing'), ('2', 'Old Report'), ('3', 'Single Car Accident'), ('4', 'Both Of Reasons')], max_length=1, null=True),
        ),
    ]
