# Generated by Django 3.1.2 on 2020-10-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20201029_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestreport',
            name='search_result',
            field=models.CharField(blank=True, choices=[('0', 'Not Existing'), ('1', 'Necessary'), ('2', 'Old Report'), ('3', 'Single Car Accident'), ('4', 'Both Of Reasons')], max_length=1, null=True),
        ),
    ]
