# Generated by Django 3.1.2 on 2020-10-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_auto_20201029_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashDrivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_report_case_no', models.CharField(max_length=20)),
                ('Drivers_full_name', models.CharField(max_length=255, null=True)),
                ('Street_Address_City_and_State', models.CharField(max_length=255, null=True)),
                ('zipcode', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('dL_state', models.CharField(max_length=35)),
                ('driving_license_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='crashreport',
            name='Drivers_full_name',
        ),
        migrations.RemoveField(
            model_name='crashreport',
            name='Street_Address_City_and_State',
        ),
        migrations.RemoveField(
            model_name='crashreport',
            name='dL_state',
        ),
        migrations.RemoveField(
            model_name='crashreport',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='crashreport',
            name='driving_license_no',
        ),
        migrations.RemoveField(
            model_name='crashreport',
            name='race',
        ),
        migrations.RemoveField(
            model_name='crashreport',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='crashreport',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='crashreport',
            name='zipcode',
        ),
    ]
