# Generated by Django 3.1.2 on 2020-10-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_auto_20201030_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreport',
            name='purchase_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
